### ISSUE TITLE
http://dashif.org/conformance.html validation fails even with --generate_dash_if_iop_compliant_mpd

### ISSUE THREAD

**Issue by kqyang** [google/edash-packager#55]
Need to look into it, find out where the problem is.

**Comment by rkuroiwa** [comment]
Used the following as input
<?xml version="1.0" encoding="UTF-8"?>
<MPD xmlns="urn:mpeg:DASH:schema:MPD:2011" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink" xsi:schemaLocation="urn:mpeg:DASH:schema:MPD:2011 DASH-MPD.xsd" xmlns:cenc="urn:mpeg:cenc:2013" minBufferTime="PT2S" type="static" profiles="urn:mpeg:dash:profile:isoff-on-demand:2011" mediaPresentationDuration="PT125.08333587646484S">
  <Period>
    <AdaptationSet id="0" contentType="video" width="720" height="360" frameRate="24000/1000" subSegmentAlignment="true" par="16:9">
      <Representation id="0" bandwidth="763873" codecs="avc1.4d001e" mimeType="video/mp4" sar="8:9" width="720" height="360" frameRate="24000/1000">
        <BaseURL>output.mp4</BaseURL>
        <SegmentBase indexRange="708-871" timescale="24000">
          <Initialization range="0-707"/>
        </SegmentBase>
      </Representation>
    </AdaptationSet>
  </Period>
</MPD>


Several reasons.

1.
I remember the MPDs failing on a DASH validation website, which I believe the DASH IF validator also uses, because the packager uses urn:mpeg:DASH:schema:MPD:2011 but the website expected urn:mpeg:dash:schema:mpd:2011. The former use to be correct (ISO/IEC 23009-1:2012) but the latest spec (2014) uses the latter.

2.
AdaptationSet@subSegmentAlignment should be subsegmentAlignment.

3.
width and height are in both AdaptationSet and Representation. Also things that can be propagated up to AdaptationSet should be in AdaptationSet.
So for the MPD, width and height should be removed from the Representation and frameRate should be bubbled up to AdaptationSet.

**Comment by rkuroiwa** [comment]
For live
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Generated with https://github.com/google/edash-packager version 2909a53-debug-->
<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink" xsi:schemaLocation="urn:mpeg:dash:schema:mpd:2011 DASH-MPD.xsd" xmlns:cenc="urn:mpeg:cenc:2013" minBufferTime="PT2S" type="dynamic" profiles="urn:mpeg:dash:profile:isoff-live:2011" availabilityStartTime="2016-01-08T21:17:55Z" minimumUpdatePeriod="PT5S" timeShiftBufferDepth="PT1800S">
  <Period start="PT0S">
    <AdaptationSet id="0" contentType="audio" segmentAlignment="true">
      <Representation id="0" bandwidth="185565" codecs="mp4a.40.2" mimeType="audio/mp4" audioSamplingRate="44100">
        <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2"/>
        <SegmentTemplate timescale="90000" initialization="live-audio.mp4" media="live-audio-$Number$.mp4" startNumber="1">
          <SegmentTimeline>
            <S t="1221005119" d="900359"/>
          </SegmentTimeline>
        </SegmentTemplate>
      </Representation>
    </AdaptationSet>
    <AdaptationSet id="1" contentType="video" maxWidth="720" maxHeight="360" frameRate="90000/3750" par="16:9">
      <Representation id="1" bandwidth="224703" codecs="avc1.64000d" mimeType="video/mp4" sar="8:9" width="368" height="184">
        <SegmentTemplate timescale="90000" initialization="live-video2.mp4" media="live-video2-$Number$.mp4" startNumber="1">
          <SegmentTimeline>
            <S t="1221500119" d="1046250"/>
          </SegmentTimeline>
        </SegmentTemplate>
      </Representation>
      <Representation id="2" bandwidth="617893" codecs="avc1.64001e" mimeType="video/mp4" sar="8:9" width="720" height="360">
        <SegmentTemplate timescale="90000" initialization="live-video.mp4" media="live-video-$Number$.mp4" startNumber="1">
          <SegmentTimeline>
            <S t="1221008869" d="982500"/>
          </SegmentTimeline>
        </SegmentTemplate>
      </Representation>
    </AdaptationSet>
  </Period>
</MPD>
```

Two errors. Both errors are due to changes from 2012 to 2014 spec.
1.
dynamic MPD must have MPD@publishTime. This is new in 2014 spec so it makes sense that we don't have it yet.

2.
dynamic MPD must have Period@id.
