### ISSUE TITLE
Multiple audio streams in live profile (question)

### ISSUE THREAD

**Issue by peyoh** [google/edash-packager#92]
Hello,
how I can insert multiple audio tracks in live profile?
Is possible?

**Comment by tinskip** [comment]
Yes, it should be possible. Pretty much the same as you do for video. You will probably want to specify the language code for each stream (language=) in addition to the bit rate.

**Comment by peyoh** [comment]
What about when the different audio streams are in the same MPEG-TS stream?

**Comment by tinskip** [comment]
Sure.  You'll just have to reference the streams by index. The index is 0 based, and for TS follows the order in which the streams are referenced in the PMT. For example video = 0, english audio = 1, spanish audio = 2, etc. When specifying the stream descriptor use stream=n instead of stream=[audio|video].

**Comment by kqyang** [comment]
You can see the list of streams with --dump_stream_info command, e.g.

```
packager input=udp://224.1.1.5:5003 --dump_stream_info
```

**Comment by peyoh** [comment]
Great!
Thank you.
